apiVersion: v2
publisher: redhat-developer
name: netcoredbg-theia-plugin
version: latest
type: VS Code extension
displayName: netcoredbg-theia-plugin
title: netcoredbg-theia-plugin
description: netcoredbg-theia-plugin
icon: /images/default.png
category: Other
repository: https://github.com/redhat-developer/netcoredbg-theia-plugin
firstPublicationDate: '2019-12-03'
latestUpdateDate: '2022-02-16'
spec:
  containers:
    - image: registry.redhat.io/codeready-workspaces/stacks-dotnet-rhel8@sha256:3fdca1ef626c6c5d452b7056afccd75722aa50ef425e4b082d18e2e92ab6bb79
      name: theia-netcoredbg
      memoryLimit: 512Mi
      memoryRequest: 20Mi
      cpuRequest: 30m
      cpuLimit: 500m
  extensions:
    - https://github.com/redhat-developer/omnisharp-theia-plugin/releases/download/v0.0.7/omnisharp_theia_plugin.theia
    - https://github.com/redhat-developer/netcoredbg-theia-plugin/releases/download/v0.0.4/netcoredbg_theia_plugin.theia
#    - relative:extension/resources/github_com/redhat-developer/netcoredbg-theia-plugin/releases/download/v0_0_3/netcoredbg_theia_plugin.theia