apiVersion: v1
kind: Service
metadata:
  labels:
    app: signalr-dotnet-deploy
  name: signalr-dotnet-deploy
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: signalr-dotnet-deploy
  type: LoadBalancer
