apiVersion: v1
kind: Service
metadata:
  labels:
    app: signalr-dotnet-deploy
  name: signalr-dotnet-deploy
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: signalr-dotnet-deploy
  type: LoadBalancer
